### PR TITLE
Demon

### PR DESCRIPTION
**Pull request by lucien1276**
My first program for the G15.
A two-dimensional cyclic cellular automaton.
This machine needs an assembler. It's the first time I hand-assemble a program: an interesting experience, but once is enough!

### CODE REVIEW

**Comment by pkimpel** [comment]
Lucien - thank you for this interesting contribution. This may be the first new, non-trivial, publicly-available program for the G-15 in over 50 years. It seems to work fine for me -- I have been running it for over an hour, and it has given the lamps on the control panel the best workout they have ever had.

I have accepted your contribution into the repository. The commit history did not seem to be worth keeping, so I a squash merge to collapse your commits into one.

I agree with your comments about needing an assembler, and that writing a program for the G-15 can be a "once is enough" experience. There actually was at least one assembler for the machine, [ALTRAN](http://bitsavers.org/pdf/bendix/g-15/APR-01621_ALTRAN_Jan62.pdf), which appears to have optimized drum locations somewhat like SOAP for the IBM 650. In other words, it assigned the N field of an instruction. It does not appear to have supported symbolic addresses, however, and did not set the T field.

I am not currently aware that a machine-readable copy of ALTRAN has survived. There is a listing with some machine language in the back of the document at the link above, but it is not clear what that code is or whether it is complete.

Thank you again for your contribution and for your interest in the retro-g15 emulator.

**Comment by pkimpel** [comment]
Lucien - I have remained very impressed with your Demon two-dimensional automaton that you wrote for my [retro-g15 emulator](https://github.com/pkimpel/retro-g15) in early 2024, especially considering you had just started working with that system. I thought you might be interested to know that a lot has been happening with the Bendix G-15 in the interim.

First, I have just finished committing some changes to the files in the [G15-software](https://github.com/retro-software/G15-software/tree/main/Demon) repository. Your original .pti file is unchanged, but I have added a second copy with your comments translated from French to English by means of Google Translate. I have also included the output from a long run of the program (14.6 hours) with the numeric cell values translated to ASCII characters of varying visual density. That does a reasonable job of showing the patterns that develop. Finally, there is a disassembly of the tape image, generated by a [tool](https://www.phkimpel.us/Bendix-G15/software/tools/Paper-Tape-Disassembler.html) that I wrote a few years ago.

Second, there is now a real G-15 system running! Around the time I started working on the emulator, the [System Source Computer Museum](https://museum.syssrc.com/) near Baltimore, Maryland (US) acquired two complete G-15 systems and a ton (literally) of documents, paper tapes, and other miscellanea for the system. In mid-2023, the museum shipped the older of its G-15s to David Lovett in Texas for restoration. 

David is the creator of the [Usagi Electric](https://www.youtube.com/results?search_query=usagi+electric+Bendix) channel on YouTube, where he rotates among various electronic and electro-mechanical restoration projects, releasing new videos approximately weekly. If you are interested, you can subscribe to early access for his videos on [Patreon](https://www.patreon.com/usagielectric), but several weeks after they are released you can view them for free. There is also an active G-15 channel on the [Usagi Electric Discord](https://discord.com/invite/p7UsfHD) server.

David has done an amazing job with the restoration of this G-15 and has had the system working quite well since the end of 2024. His work has stimulated much of the recent growth of interest in the G-15. His current plan is to clean up some loose ends of the restoration, ship that system back to the museum later this year, and then receive their other G-15 for its restoration.

Third, with the restoration of the first G-15 nearing completion, David would like to produce an episode that highlights some examples of G-15 programming. May I have your permission to submit your Demon program for that episode on your behalf? Please let me know. If you agree, please know that I can't guarantee whether David will actually include it in the episode.

Finally, I made a change to the emulator two months ago that I discovered this past week broke your Demon program. The bug was associated with executing a TYPE AR command when there was no STOP code in the format string in line 03. I found the problem yesterday, and plan to release the fix later today as version 1.09.

If you would like to correspond directly, my email is paul.kimpel@digm.com.

**Comment by lucien1276** [comment]
Thank you for taking care of my program!
I know Usagi well, I follow his channel faithfully every Sunday. It's because of his enthusiasm that I came across your emulator. For sure, I'd be honored to have my program run on a real G15.
I haven't completely given up on the G15, I've started to make a PPR in javascript.
Then I was diverted to another project: https://forums.atariage.com/topic/381529-ti-logo-improvements

**Comment by pkimpel** [comment]
Lucien - I am having to do some major work on my G-15 emulator and in the process discovered that what I told you about the TYPE AR command in [my notification of 14 July](https://github.com/retro-software/G15-software/pull/1#issuecomment-3070210858) was wrong.

Previously, I had been terminating a TYPE AR command when either an END format code was encountered or once 7 hex digits had been output. That behavior is incorrect -- TYPE AR terminates only when an END format code is encountered. It is your Demon program that had a problem after all.

Your program stores multiple typewriter formats in line 03. I found four of them, two that have END format codes, and two that do not (see the code for line 1, words 49 and 50). The two without END codes cause the typewriter to print the contents of AR, then continuously print zeroes until you cancel the I/O with ENABLE-S. This is because output from AR shifts zeroes into the low-order end of AR as digits are precessed from the high-order end of the register to be printed, After 7 digits, AR has been completely shifted to the left and further precessions result in zeroes.

The fix is to add END codes to the format words that get stored in 03.03. I have modified your `.pti` file and added comments to show where I have made changes. A copy of the [updated `.pti` file](https://github.com/user-attachments/files/23630377/demon-English.pti.TXT) is attached.

I ran this version for a few hours last night, and it generates the same results as before. I have not committed this change to the [retro-software repository](https://github.com/retro-software/G15-software) yet. I wanted to give you a chance to review the changes first. I'll remove my comments from the `.pti` file and move them to the commit memo when I do make a commit.

I have also not updated the emulator code with the TYPE AR change on the hosting site yet, as G-15 software with properly coded typewriter formats already work properly. That update will not happen until I finish the work I'm currently doing on the emulator, which may take a while yet.

The purpose of the current emulator task is to fix the internal timing so that certain programs such as INTERCOM and ALGO will work properly. Those programs play crazy tricks with line 19 while I/Os are in progress. Those tricks rely on very accurate synchronization of drum access between the processor and I/O subsystem. The original design of the emulator synchronizes the processor and I/O at the start of an I/O operation, but after that the two can drift out of synchronization, which causes at least INTERCOM to print floating-point number incorrectly. I'm trying to fix this without having to completely rewrite the processor and I/O subsystem. The change is implemented in my development system, but debugging it is proving to be a challenge. I'll make a post on the Discord channel once this is task finished.

**Comment by lucien1276** [comment]
I have reviewed your changes. Fortunately, it only involves changing two constant values, rather than inserting instructions into highly optimized code ;)
I don't remember why I added END in only two places. I suppose it's because I'm minimalist and like to experiment. If it works without the END format code, why include it? (even though the documentation probably says otherwise).
You can commit the changes. Thanks again for taking care of my program!

**Pull request merged**
